# Describes the services offered by the SNCB/NMBS integration
refresh_data:
  name: Refresh data
  description: Force refresh of train data for all configured connections.
  target:
    entity:
      integration: belgiantrain
      domain: sensor
